### ISSUE TITLE
tutorial2

### ISSUE THREAD

**Issue by Bernard13090** [AlanFord/ZapMeNot#17]
Hi,

amazing !

I solve WatpropPy with Google.

**I m trying example [ZapMeNot](https://github.com/AlanFord/ZapMeNot)/[tutorial](https://github.com/AlanFord/ZapMeNot/tree/master/tutorial)/tutorial2.ipynb and have an issue at the end.**

Calculate Dose Rate
1
result = tank_model.calculate_exposure()
2
display(Markdown(f"**dose rate = {result:2.3} mR/hr**"))
dose rate = 7.44 mR/hr

Plot the Geometry
1
pv.set_jupyter_backend('ipygany')
2
tank_model.display()
C:\Users\Bernard\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel_launcher.py:1: PyVistaDeprecationWarning: `ipygany` backend is deprecated and is planned for future removal.
  """Entry point for launching an IPython kernel.
**C:\Users\Bernard\AppData\Local\Programs\Python\Python37\lib\site-packages\traittypes\traittypes.py:101: UserWarning: Given trait value dtype "float32" does not match required type "float64". A coerced copy has been created.
  np.dtype(self.dtype).name))**
Scene(background_color='#4c4c4c', camera={'position': [794.5694292875173, 589.0665987821462, 681.4209917875173…

at the end

i change to:

import pyvista as pv
pv.set_jupyter_backend('trame')
tank_model.display()

and it's work !

**Comment by AlanFord** [comment]
Thanks for the info!  Other folks are having difficulties with Jupyter graphics - I'll test this out and likely recommend it to them.  Are you using MS Windows?  Most of ZapMeNot development has been done on MacOS and Linux, so testing with Windows has been somewhat limited.  As for WatpropPy, testing was done exclusively on RedHat Linux.  I may pull references to WatpropPy out of the ZapMeNot tutorials, as it's convenient, but not required, to get water densities.
