### ISSUE TITLE
output units

### ISSUE THREAD

**Issue by AlanFord** [AlanFord/ZapMeNot#5]
reporting exposure in R/sec is pretty useless.  Consider converting to mR/hr.

**Comment by AlanFord** [comment]
Output units are not mR/hr

**Comment by Paidaxing123321** [comment]
Is the unit of the output result mR/h mRem/h, and if I need to convert it to uSv/h should I x 10 the result?

**Comment by AlanFord** [comment]
> Is the unit of the output result mR/h mRem/h, and if I need to convert it to uSv/h should I x 10 the result?

Yes, that would be correct.  Unfortunately we are not using metric units in the US power industry.
